<?php

/**
 * @file
 * Contains ngt_general.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ngt_general_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the ngt module.
        case 'help.page.ngt_general':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('ngt general') . '</p>';
        return $output;

    default:
    }
}



/**
 * Implements hook_preprocess().
 * 
 * Prepares variables for the html.html.twig template.
 * Inlcuye la directiva de angular la etiqueta html
 * 
 */
function ngt_general_preprocess_html(&$variables){
  $variables['html_attributes']['data-ng-app'] = 'ngtApp';

  $routeName = \Drupal::routeMatch()->getRouteName();
  $showHeaderAndFooter = true;
  $menuActiveUser = 'no-active';
  $menuActiveNode = 'no-active';

  if($routeName == 'entity.node.canonical'){
    $menuActiveNode = 'active';
  }

  //adición angular en page no customizadas
  // switch ($routeName) {
  //   case 'entity.node.canonical':
  //   case 'entity.user.canonical':

  //       $variables['#attached']['library'][] = 'ngt_general/angular.ngt';
  // }

  $variables['#attached']['library'][] = 'ngt_general/angular.ngt';

  $variables['showHeaderAndFooter'] = $showHeaderAndFooter;
  $variables['route_name'] = \Drupal::routeMatch()->getRouteName();
  $variables['menuActiveUser'] = $menuActiveUser;
  $variables['menuActiveSearch'] = 'no-active'; // pendiente ajustar cuando se genere el buscador
  $variables['menuActiveNode'] = $menuActiveNode;


  // global variables
  $config = \Drupal::config('ngt_general.settings');  
  
  $logo_general_fid = reset($config->get('general_settings')['img_logo']);
  $logo_general_file = File::load($logo_general_fid);
  $logo_general_url = isset($logo_general_file) ? $logo_general_file->getFileUri() : '';

  $logo_mobile_fid = reset($config->get('general_settings')['img_logo_mobile']);
  $logo_mobile_file = File::load($logo_mobile_fid);
  $logo_mobile_url = isset($logo_mobile_file) ? $logo_mobile_file->getFileUri() : '';

  $logo_second_fid = reset($config->get('general_settings')['img_logo_second']);
  $logo_second_file = File::load($logo_second_fid);
  $logo_second_url = isset($logo_second_file) ? $logo_second_file->getFileUri() : '';

  $logo_design_fid = reset($config->get('general_settings')['img_logo_design_by']);
  $logo_design_file = File::load($logo_design_fid);
  $logo_design_url = isset($logo_design_file) ? $logo_design_file->getFileUri() : '';

  $activate_img_logo_second = $config->get('general_settings')['activate_img_logo_second'];

  $script_external = $config->get('script_settings')['external'];
  $general_txt_footer  = $config->get('other_settings')['txt_footer'];

  $variables['logo_general_url'] = $logo_general_url;
  $variables['logo_mobile_url'] = $logo_mobile_url;
  $variables['logo_second_url'] = $logo_second_url;
  $variables['logo_design_url'] = $logo_design_url;
  $variables['activate_img_logo_second'] = $activate_img_logo_second;
  $variables['script_external'] = $script_external;
  $variables['general_txt_footer'] = $general_txt_footer;

}

